baseURL = 'https://example.org/'
languageCode = 'ru-ru'
title = 'Кот Не Работает'
theme = 'hyde'

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/rokkerruslan"},
      {Name = "Matrix", URL = "https://matrix.to/#/@rokkerruslan:matrix.org"},
      {Name = "Email", URL = "mailto:rokkerruslan@protonmail.com"},
      {Name = "LinkedIn", URL = "https://linkedin.com/in/rokkerruslan"}
  ]

[params]
  description = 'Сказки для инженеров-программистов младшего уровня'
