baseURL = 'https://rokkerruslan.github.io'
languageCode = 'ru-ru'
theme = 'gobuchtm'

[markup]
  [markup.highlight]
  style = 'github-dark'
  tabWidth = 3

[params]
  brand = 'Кот Не Работает'
  description = 'Сказки для инженеров-программистов младшего уровня'

  dark_mode = false
  menu = [
    {Name = 'Заметки', URL = '/posts/', HasChildren = true, Limit = 5}
  ]

  matrix_url = 'https://matrix.to/#/@rokkerruslan:matrix.org'
  github_url = 'https://github.com/rokkerruslan'
  email_url = 'mailto:rokkerruslan@protonmail.com'
  linkedin_url = 'https://linkedin.com/in/rokkerruslan'
